version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: campus-connect-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: campus-connect
    ports:
      - '5444:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
