services:
  - type: web
    name: campus-connect-api
    env: node
    region: oregon
    plan: free
    rootDir: apps/api
    buildCommand: cd ../.. && pnpm install --no-frozen-lockfile && pnpm --filter @campus-connect/types build && pnpm --filter @campus-connect/utils build && pnpm --filter @campus-connect/api build
    startCommand: node dist/main
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_CqAk4MXOsy5v@ep-quiet-bonus-au6m8rwv.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require&connect_timeout=15
      - key: COLLEGE_A_DATABASE_URL
        value: postgresql://neondb_owner:npg_CqAk4MXOsy5v@ep-quiet-bonus-au6m8rwv.c-10.us-east-1.aws.neon.tech/campus_connect_db_a?sslmode=require&connect_timeout=15
      - key: COLLEGE_B_DATABASE_URL
        value: postgresql://neondb_owner:npg_CqAk4MXOsy5v@ep-quiet-bonus-au6m8rwv.c-10.us-east-1.aws.neon.tech/campus_connect_db_b?sslmode=require&connect_timeout=15
      - key: COLLEGE_C_DATABASE_URL
        value: postgresql://neondb_owner:npg_CqAk4MXOsy5v@ep-quiet-bonus-au6m8rwv.c-10.us-east-1.aws.neon.tech/campus_connect_db_c?sslmode=require&connect_timeout=15
      - key: JWT_SECRET
        value: super-secret-jwt-key-for-campus-connect
      - key: REDIS_URL
        value: rediss://default:gQAAAAAAAXpJAAIgcDEzMDU0ZmY1NWEwZjc0ODdhYWJmMWI2NGY2YmU1NDE5OA@on-owl-96841.upstash.io:6379
      - key: MULTI_DB_ENABLED
        value: true
      - key: CLOUDINARY_CLOUD_NAME
        value: poqayuww
      - key: CLOUDINARY_API_KEY
        value: "636825337839938"
      - key: CLOUDINARY_API_SECRET
        value: 6H1RURbZ36cg028rqRz6O34XVKg
      - key: CLOUDINARY_URL
        value: cloudinary://636825337839938:6H1RURbZ36cg028rqRz6O34XVKg@poqayuww
      - key: ENABLE_SWAGGER
        value: true
      - key: ALLOWED_ORIGINS
        value: https://campus-connect-web-tau.vercel.app,http://localhost:3000,http://localhost:3001
