services:
  - type: web
    name: campus-connect-api
    env: node
    region: oregon
    plan: free
    rootDir: apps/api
    buildCommand: cd ../.. && pnpm install --frozen-lockfile && pnpm --filter @campus-connect/types build && pnpm --filter @campus-connect/utils build && pnpm --filter @campus-connect/api prisma:generate && pnpm --filter @campus-connect/api build
    startCommand: node dist/main
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_Lth9w8nWeZlg@ep-delicate-fog-aebcogwo-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&connect_timeout=30
      - key: MULTI_DB_ENABLED
        value: "false"
      - key: SINGLE_DB_MODE
        value: "true"
      - key: ALLOWED_ADMIN_EMAILS
        value: anish@college.edu,teacher@college.edu,admin@collegea.edu,admin@collegeb.edu,super@campusconnect.com
      - key: JWT_SECRET
        value: super-secret-jwt-key-for-campus-connect
      - key: REDIS_URL
        value: rediss://default:gQAAAAAAAXpJAAIgcDEzMDU0ZmY1NWEwZjc0ODdhYWJmMWI2NGY2YmU1NDE5OA@on-owl-96841.upstash.io:6379
      - key: CLOUDINARY_CLOUD_NAME
        value: poqayuww
      - key: CLOUDINARY_API_KEY
        value: "636825337839938"
      - key: CLOUDINARY_API_SECRET
        value: 6H1RURbZ36cg028rqRz6O34XVKg
      - key: CLOUDINARY_URL
        value: cloudinary://636825337839938:6H1RURbZ36cg028rqRz6O34XVKg@poqayuww
      - key: ENABLE_SWAGGER
        value: "true"
      - key: ALLOWED_ORIGINS
        value: https://campus-connect-web-tau.vercel.app,http://localhost:3000,http://localhost:3001
      - key: MONGODB_ENABLED
        value: "true"
      - key: MONGODB_URI
        value: mongodb://campusconnect:anishsantoshpatil123@ac-g7ss8v3-shard-00-00.hjyjapj.mongodb.net:27017,ac-g7ss8v3-shard-00-01.hjyjapj.mongodb.net:27017,ac-g7ss8v3-shard-00-02.hjyjapj.mongodb.net:27017/?ssl=true&replicaSet=atlas-abo4jb-shard-0&authSource=admin&appName=Cluster0
      - key: MONGODB_DB_NAME
        value: campus_connect_aux
