$pnpmAndroid = "C:\Users\USER\OneDrive\Desktop\campus-connect\node_modules\.pnpm\expo-modules-core@3.0.30_react-native@0.81.5_@babel+core@7.29.7_@react-native-community+cli@1_a2otg36iinjkdjbnvddxa5b2aa\node_modules\expo-modules-core\android"
$cmakeOut = $pnpmAndroid + "\build\intermediates\cxx\Debug\arm64-v8a"
$prefabCmd = $cmakeOut + "\.cxx\cmake\debug\arm64-v8a\prefab_command.bat"
$prefabFull = "C:\Users\USER\OneDrive\Desktop\campus-connect\apps\mobile\android\build\intermediates\cxx\Debug\arm64-v8a\.cxx\cmake\debug\arm64-v8a\prefab_command.bat"

Write-Host "=== Path Length Analysis ==="
Write-Host ""
Write-Host "[pnpm android source] $($pnpmAndroid.Length) chars:"
Write-Host "  $pnpmAndroid"
Write-Host ""
Write-Host "[CMake intermediates output in pnpm path] $($cmakeOut.Length) chars:"
Write-Host "  $cmakeOut"
Write-Host ""
Write-Host "[prefab_command.bat in pnpm path] $($prefabCmd.Length) chars:"
Write-Host "  $prefabCmd"
Write-Host ""
Write-Host "[prefab_command.bat in app android dir] $($prefabFull.Length) chars:"
Write-Host "  $prefabFull"
Write-Host ""
Write-Host "=== Windows MAX_PATH = 260 chars ==="
Write-Host "pnpm android path over limit: $($pnpmAndroid.Length -gt 260)"
Write-Host "CMake out path over limit: $($cmakeOut.Length -gt 260)"
Write-Host "prefab_command.bat (pnpm) over limit: $($prefabCmd.Length -gt 260)"
Write-Host "prefab_command.bat (app) over limit: $($prefabFull.Length -gt 260)"
Write-Host ""
Write-Host "=== OneDrive Detection ==="
$oneDrivePath = "C:\Users\USER\OneDrive"
Write-Host "Project is inside OneDrive path: $($pnpmAndroid.StartsWith($oneDrivePath))"
Write-Host ""
Write-Host "=== Long Path Registry Check ==="
$regVal = (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -ErrorAction SilentlyContinue).LongPathsEnabled
Write-Host "LongPathsEnabled registry value: $regVal"
Write-Host ""
Write-Host "=== Gradle JAVA_HOME / Java Version ==="
java -version 2>&1
Write-Host ""
Write-Host "=== ANDROID_HOME ==="
Write-Host "ANDROID_HOME = $env:ANDROID_HOME"
Write-Host "ANDROID_SDK_ROOT = $env:ANDROID_SDK_ROOT"
